### ISSUE TITLE
credit

### ISSUE THREAD

**Issue by ethanlindley** [itsinfinity/ToontownLegacy#1]
u should probs give some credit first before publicizing our code without permission

**Comment by itsinfinity** [comment]
I dont have too. You see. This is stolen code. Yes its 2003 but look here.... https://prnt.sc/gvs9j0 OTPLocalizerEnglish. Elections? Huh thats interesting.. You sure thats not TTR... and then! WHATS THIS https://prnt.sc/gvs96v REFERENCES TO TOONTOWN HOUSE? But tth wasnt a thing in 2003... I guess Time machine. It must be very hard to pull the localizers from 2003 then...

**Comment by ethanlindley** [comment]
Regardless of the fact that we copied code that contained mostly strings for the game (which is practically the same across each and every emulator), you can't release code that isn't yours. I gave you access to the source, allowed you to use it in private projects, but did not permit you to open - source our code.

I'm not asking you to take the repository down. All I'm asking is that you give us credit, which has nothing to do with the fact that yes, we did in fact copy code from two minuscule modules that contain strings and text for ToonTown Online.

**Comment by AlexTheGreat12** [comment]
Guess i should email disney then we cant releasee their code.

**Comment by itsinfinity** [comment]
Sorry about that. I have had a bad day.  Ill give credit.

**Comment by ethanlindley** [comment]
Thanks!

**Comment by itsinfinity** [comment]
Is toontown legacy still a thing? I wrote a otp for the  2003 client. I wanted to finish this though.

**Comment by itsinfinity** [comment]
https://github.com/itsinfinity/ToontownLegacy/commit/1ab6e59916ecee9c694841e7cdd45142d7e41724

**Comment by ethanlindley** [comment]
A few of my developers at Legacy Studios and I work on it from time to time. Our main project currently is Pirates Online Legacy, a recreation of Pirates of the Caribbean Online using assets from the 2008 client.
